### ISSUE TITLE
Error activating env

### ISSUE THREAD

**Issue by marcosmoyano** [necaris/conda.el#130] opened 2022-08-10 14:58 UTC
After a Doom emacs update (which updated conda.el) I'm getting this error trying to activate an environment with `conda-env-activate`.

```shell
❯ conda --version
conda 4.13.0
```

```lisp
Debugger entered--Lisp error: (error "Invalid version syntax: ‘Error’ (must start with a number)")
  error("Invalid version syntax: `%s' (must start with a number)" "Error")
  version-to-list("Error")
  version<("4.8.3" "Error")
  conda--supports-json-activator()
  conda--get-deactivation-parameters("/home/marcos/.conda/envs/myenv/")
  conda-env-deactivate()
  conda-env-activate-path("/home/marcos/.conda/envs/myenv/")
  conda-env-activate()
  funcall-interactively(conda-env-activate)
  command-execute(conda-env-activate record)
  counsel-M-x-action("conda-env-activate")
  #f(compiled-function (x) #<bytecode -0x18f9a15a30bf8500>)("conda-env-activate")
  ivy-call()
  #<subr ivy-read>("M-x " ("conda-env-activate" "conda-env-list" "vc-annotate" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" "ediff" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t)
  apply(#<subr ivy-read> ("M-x " ("conda-env-activate" "conda-env-list" "vc-annotate" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" "ediff" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x :sort t))
  ivy-read("M-x " ("conda-env-activate" "conda-env-list" "vc-annotate" "cd" "5x5" "amx" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "lsp" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "lsp!" "mail" "mpuz" "ping" "pong" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" "ediff" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)
```

Any idea what might be causing this? Thx in advance.

**Comment by marcosmoyano** [comment] 2022-08-10 17:14
X-Ref: https://github.com/doomemacs/doomemacs/issues/6658

**Comment by necaris** [comment] 2022-08-10 17:32
Could you let me have the results of `conda info` and `doom info` please?

**Comment by marcosmoyano** [comment] 2022-08-10 17:59
doom info
```
❯ ~/.emacs.d/bin/doom info
generated  Aug 10, 2022 14:58:53
system     Arch Linux Linux 5.15.55-1-lts x86_64
emacs      28.1.50 makepkg 372341574 ~/.emacs.d/ -> ~/.emacs.d/
doom       3.0.0-dev grafted, HEAD -> master, origin/master, origin/HEAD 12bf6ba 2022-08-10 17:29:01 +0200 ~/.doom.d/ -> ~/.doom.d/
shell      /usr/bin/zsh
features   ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF
           TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB
traits     batch envvar-file custom-file
modules    :completion company (ivy +prescient +icons) :ui doom doom-dashboard doom-quit (emoji +unicode +github +ascii) hl-todo hydra modeline (popup +defaults) vc-gutter
           vi-tilde-fringe (window-select +numbers) :editor file-templates fold (format +onsave) snippets word-wrap :emacs (dired +icons) (ibuffer +icons) undo vc :term vterm
           :checkers syntax :tools (debugger +lsp) (eval +overlay) lookup lsp magit terraform :os tty :lang emacs-lisp json javascript markdown org (python +conda +ipython +lsp) sh
           web yaml :config (default +bindings +snippets)
packages   (undo-tree) (git-link) (python-black) (sql-indent)
```

conda info
```
❯ conda info

     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /home/marcos/.condarc
 populated config files : /home/marcos/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.55=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/marcos/.conda/pkgs
       envs directories : /home/marcos/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.12 Linux/5.15.55-1-lts arch/ glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

    ~
```

**Comment by marcosmoyano** [comment] 2022-08-11 14:36
@necaris were you able to reproduce? is there anything I can do/try ?

**Comment by necaris** [comment] 2022-08-14 19:18
@marcosmoyano apologies for the delay, I was out of town. I'm unfortunately not able to reproduce -- from the traceback, it looks like `conda -V` is returning an error for you. Can you try both `which -a conda` (to make sure it's calling the right executable) and `conda -V` (to debug the output of the command)?

**Comment by marcosmoyano** [comment] 2022-08-16 13:27
```bash
❯ which -a conda
conda () {
        \local cmd="${1-__missing__}"
        case "$cmd" in
                (activate | deactivate) __conda_activate "$@" ;;
                (install | update | upgrade | remove | uninstall) __conda_exe "$@" || \return
                        __conda_reactivate ;;
                (*) __conda_exe "$@" ;;
        esac
}
/opt/miniconda3/bin/conda
/opt/miniconda3/condabin/conda
    ~
❯ diff /opt/miniconda3/bin/conda /opt/miniconda3/condabin/conda
    ~
❯ conda -V
conda 4.13.0
    ~
```

Is this helpful ?

**Comment by marcosmoyano** [comment] 2022-08-26 16:02
@necaris bump ?

**Comment by necaris** [comment] 2022-08-29 16:08
@marcosmoyano any chance you could try out this branch and let me know of any errors? https://github.com/necaris/conda.el/pull/133

**Comment by marcosmoyano** [comment] 2022-08-29 17:59
Sure thing. I'll give a shot later today and report back

**Comment by marcosmoyano** [comment] 2022-08-29 18:27
BTW, conda 4.12.0 and 4.14.0 don't have this issue. I'd be ok closing this at this point. But also, happy to keep digging with 4.13 to get to the bottom of this.

**Comment by necaris** [comment] 2022-08-29 19:07
If you don't mind trying once to see what kind of errors come up with
4.13 I'd appreciate it -- just to have for future reference if other
folks run across this issue.

Marcos Moyano ***@***.***> writes:

> BTW, conda 4.12.0 and 4.14.0 don't have this issue. I'd be ok closing this at this point. But also, happy to keep digging with 4.13 to get to the bottom of this.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


--
Rami Chowdhury
A mind all logic is like a knife all blade - it makes the hand bleed that uses it.
  -- Rabindranath Tagore

**Comment by marcosmoyano** [comment] 2022-08-30 14:32
mmm now I'm not able to reproduce with conda 4.13.0. Don't know what I changed that fixed it. The only difference I see is in the output  of `conda info`. `shell level` is now 0 and it was 1 previously. That's the only difference.

**Comment by necaris** [comment] 2022-08-30 15:06
That could be something! Shell level 1 indicates that a conda
environment is _already_ activated; is it possible you had already
activated an environment before you started Emacs previously?

Marcos Moyano ***@***.***> writes:

> mmm now I'm not able to reproduce with conda 4.13.0. Don't know what I changed that fixed it. The only difference I see is in the output of conda info. shell
> level is now 0 and it was 1 previously. That's the only difference.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.


--
Rami Chowdhury
A mind all logic is like a knife all blade - it makes the hand bleed that uses it.
  -- Rabindranath Tagore

**Comment by marcosmoyano** [comment] 2022-08-30 15:12
maybe? either way I can't reproduce it anymore 🤷🏼‍♂️

**Comment by necaris** [comment] 2022-08-30 15:47
Okie dokie, closing :smile:

**Closed by necaris** 2022-08-30 15:47 UTC
Labels: bug

**Comment by kantholtz** [comment] 2023-11-20 09:14
Sorry to resurrect this from the dead, but I am plagued by the same error on the latest `miniconda` release:

```elisp
Debugger entered--Lisp error: (error "Invalid version syntax: ‘conda’ (must start with a number)")
  error("Invalid version syntax: `%s' (must start with a number)" "conda")
  version-to-list("conda")
  version<("4.8.3" "conda")
  conda--supports-json-activator()
  conda--get-deactivation-parameters("/home/felix/Complex/opt/conda/")
  conda-env-deactivate()
  conda-env-activate-path("/home/felix/Complex/opt/conda/envs/lyg/")
  conda-env-activate()
  funcall-interactively(conda-env-activate)
  command-execute(conda-env-activate record)
  #<subr execute-extended-command>(nil "conda-env-activate" "con")
  ad-Advice-execute-extended-command(#<subr execute-extended-command> nil "conda-env-activate" "con")
  apply(ad-Advice-execute-extended-command #<subr execute-extended-command> (nil "conda-env-activate" "con"))
  execute-extended-command(nil "conda-env-activate" "con")
  funcall-interactively(execute-extended-command nil "conda-env-activate" "con")
  god-mode-self-insert()
  funcall-interactively(god-mode-self-insert)
  command-execute(god-mode-self-insert)
```

```console
$ conda --version
conda 23.10.0
```

Please let me know if/how I can provide any more info.
