### ISSUE TITLE
Cannot activate any env on OSX

### ISSUE THREAD

**Issue by kittipatv** [necaris/conda.el#39] opened 2019-07-22 02:02 UTC
I'm not sure if I did something wrong but I can't activate anything on OSX. I have 2 envs on my systems:

```
$ conda info -e
# conda environments:
#
base                  *  /Users/kittipat/miniconda3
test_env                 /Users/kittipat/miniconda3/envs/test_env
```

When I ran `conda-env-list`, I got an empty buffer. I do have `(custom-set-variables
 '(conda-anaconda-home "~/miniconda3/"))` in my init file. 

Here are some version infos:

```
$ emacs --version
GNU Emacs 26.2
$ conda --version
conda version : 4.7.10
python version : 3.7.3.final.0
```

I got `conda.el` from MELPA.

**Comment by sampotter** [comment] 2019-08-11 16:18
I'm having the same problem. Any thoughts about how to fix this?

**Comment by sampotter** [comment] 2019-09-13 13:31
Hmm, problem seems to be fixed for me! I haven't tried this since my last message here, but just reinstalled conda.el, and it's also possible I'm using a new version of Emacs since then.

At the time of the problem, I _was_ using exec-path-from-shell, in case that helps.

**Comment by necaris** [comment] 2019-09-16 00:47
@kittipatv are you still seeing this problem?

**Comment by zjp** [comment] 2019-09-17 16:57
I'm currently having this issue. It seems like the docs expect the package to be in ~/ but homebrew sticks anaconda in /usr/local/ -- I took ownership of the directory but it looks like it isn't reading the environments there.

**Comment by necaris** [comment] 2019-09-17 17:05
@zjp thank you, that's a really helpful clue! Can you try telling `conda.el` where to find your Anaconda installation by setting the `conda-anaconda-home` customizable variable? You can set this in your `.emacs` / `init.el` with:
```elisp
(custom-set-variables
 '(conda-anaconda-home "/path/to/my/Anaconda"))
```
Or, to update the value in your current session, try `M-x customize-variable RET conda-anaconda-home RET` and enter the correct path there.

Once you've done this, are you able to activate an environment?

**Comment by zjp** [comment] 2019-09-17 17:09
I had had that variable set to `/usr/local/anaconda3` (after I took ownership of the folder) -- I tried also adding `/usr/local/anaconda3/envs` to `conda-env-home-directory` but couldn't get the menu to populate.

**Comment by necaris** [comment] 2019-09-17 17:11
@zjp any chance you can paste the contents of your `*Messages*` buffer after you try `conda-env-activate`?

**Comment by zjp** [comment] 2019-09-17 17:34
There is no output that I can see.

**Comment by zjp** [comment] 2019-09-19 04:49
Hmmm... I'm not sure what I did, but I rebuilt my Emacs init file and miraculously, it now finds environments in /usr/local/anaconda3. Regrettably, I'm not sure what exactly I did or I'd state what it was to try and help the original user.

**Comment by necaris** [comment] 2019-09-20 17:34
@zjp thank you for the update! Since two of the three people who reported the issue are reporting it's fixed now, I'm going to go ahead and close it -- @kittipatv if you are still seeing this problem please reopen!

**Comment by SergiyKolesnikov** [comment] 2019-11-10 17:24
I worked around this issue by setting `conda-env-home-directory` to the same value as `conda-anaconda-home` in the `init.el`.

I believe, the regression was introduced in 2c271967871b7e114cc41198a945b1e11c3e4c64 and affects configurations with non-default `conda-anaconda-home` (e.g., `/opt/anaconda3/` instead of the default `~/.anaconda3/`).

For a non-default Anaconda path, the documentation instructs to set only `conda-anaconda-home` in `init.el`, but `conda-env-home-directory` still gets the default path from `conda-anaconda-home` when the mode is initialized:
https://github.com/necaris/conda.el/blob/2c271967871b7e114cc41198a945b1e11c3e4c64/conda.el#L47-L48

An easy fix would be to update the docs accordingly, but it would be nice if `conda-env-home-directory` were updated automatically in case only `conda-anaconda-home` is customized.

**Comment by necaris** [comment] 2019-11-12 02:25
@SergiyKolesnikov since you appear to have found an underlying cause I'm reopening this to take a deeper look when I get a minute -- thank you!

**Comment by SergiyKolesnikov** [comment] 2019-11-14 12:25
@necaris thanks for looking into this. Just wanted to note that this issue is not OSX specific, I am using Debian 10.

**Comment by simenojensen** [comment] 2019-11-17 23:53
@necaris, I am having a similar problem.

These are my configs:
  
`(use-package conda
    :config
    (setq conda-anaconda-home "/usr/local/Caskroom/miniconda")
    (setq conda-env-home-directory "/usr/local/Caskroom/miniconda")
    (conda-env-initialize-interactive-shells)
    (conda-env-initialize-eshell))
`
I am also using =exec-path-from-shell=.

=M-x conda-env-list= is empty
=M-x conda-env-activate-path= lets me choose an environment from my file directory. But when I try to =M-x conda-env-activate= it, I receive the following error message:

Debugger entered--Lisp error: (error "No such conda environment: ")
  signal(error ("No such conda environment: "))
  error("No such conda environment: %s" "")
  conda-env-name-to-dir("")
  conda-env-is-valid("")
  conda-env-activate()
  funcall-interactively(conda-env-activate)
  call-interactively(conda-env-activate record nil)
  command-execute(conda-env-activate record)
  counsel-M-x-action("conda-env-activate")
...

**Comment by hnisonoff** [comment] 2019-11-28 04:02
I am also having this same problem.

**Comment by ivan-krukov** [comment] 2019-12-06 19:39
Aside, from the comments from @SergiyKolesnikov, there is an issue of how the env dirs are validated.

The `conda--env-dir-is-valid` function checks if the candidate directory contains `bin` or `Scripts` (on windows). It seems that those will not necessarily be contained by the environment dirs. Simply adding a `bin` dummy subdirectory into `~/<condapath>/envs/my-env/` makes `my-env` discoverable by `conda-env-activate`.

I think that the only subdir that a conda env should contain is `conda_meta` (or at least this appears to be the case on my machine.

**Comment by hnisonoff** [comment] 2019-12-17 18:43
I had to change
```
(setq conda-env-home-directory (expand-file-name "~/anaconda3/envs")
	)```
to 
```
(setq conda-env-home-directory (expand-file-name "~/anaconda3/")
	)
```

**Comment by simenojensen** [comment] 2020-02-25 19:44
For miniconda installed with Homebrew, this fixed the error:

(setq conda-anaconda-home "/usr/local/Caskroom/miniconda/base/")

**Comment by c02y** [comment] 2020-04-12 17:03
`M-x conda-env-list` show no result, but in terminal `conda env list` show 3 envs including base env.

**Comment by simenojensen** [comment] 2020-06-11 11:24
Mac OS - Homebrew - miniconda update:
Homebrew now installs miniconda under /opt.

This works for me now:
 (setq conda-anaconda-home "/opt/miniconda3/")

**Comment by mightydeadunicorn** [comment] 2020-07-31 13:36
> I had to change
> 
> ```
> (setq conda-env-home-directory (expand-file-name "~/anaconda3/envs")
> 	)
> ```
> 
> to
> 
> ```
> (setq conda-env-home-directory (expand-file-name "~/anaconda3/")
> 	)
> ```

@hnisonoff Thank you! I'd like to add that the same solution is valid under spacemacs, this is required under `dotspacemacs-configuration-layers`:

```(conda :variables conda-anaconda-home (expand-file-name "~/anaconda3") conda-env-home-directory (expand-file-name "~/anaconda3"))```

**Comment by necaris** [comment] 2020-09-20 17:46
Does https://github.com/necaris/conda.el/commit/335474e409774e31125fe320a4a54c8d92bf5fa2 add enough documentation to be able to work around this issue? I'd like to close if so.

**Comment by funnell** [comment] 2021-11-12 15:55
hi @necaris, like others here I had to set `conda-env-home-directory` which wasn't clear from the current README. My anaconda directory is in `~/miniconda3` and from the documentation I mistakenly thought that if my env dir was in `~/miniconda3/envs` (as it is for me) then I didn't need to also set `conda-env-home-directory`.

**Comment by necaris** [comment] 2022-03-13 03:34
@funnell @simenojenson @c02y are you folks still having issues, or does this work for you all now?

**Closed** 2022-06-28 19:06 UTC
Labels: bug
